

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';

export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';

export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';


export const GET_AVATAR_REQUEST = 'GET_AVATAR_REQUEST';

export const GET_AVATAR_SUCCESS = 'GET_AVATAR_SUCCESS';

export const GET_AVATAR_ERROR = 'GET_AVATAR_ERROR';



export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';

export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';

export const UPDATE_USER_PROFILE_ERROR = 'UPDATE_USER_PROFILE_ERROR';
